### ISSUE TITLE
Collection problem when cached.

### ISSUE THREAD

**Issue by CodeLikeAManiac** [mehalick/OrangeJetpack.Localization#8]
Hi,

This is a great library but I am facing a problem which I am not sure if it can be resolve.

Let me know if you have any ideas, see the scenario below :+1: 

I am pulling data from the database and I save it into cache.
At the initial pull the translation field has an XML format.
Later on I want to convert my Collection to  another language  so I pull the data from cache and I store it into variable a variable named: **Customer**.

Then I create a _new instance_ of that type ie. List(Customer) **tempCustomer** = new List(Customer)();
and i _assign the cached object_ into the new variable:

**tempCustomer = Customer;**

At the next step I am trying to localise the variable tempCustomer **==>**

tempCustomer.Localize<Customer>("EN", i => i.TranslationName).ToList();

> Here is where things go wrong instead of localising only the collection stored into  tempCustomer  the localization affects both  objects the cache item and the new temporary variable.
> 
> So I end up having tempCustomer and Customer localized.

Is there a workaround for this ?

Thanks anyhow for the Library :1st_place_medal:

**Comment by mehalick** [comment]
The problem is that the `List<Customer>` is a reference type and your new instance is really a pointer back to the original object. So changes to either are really changing a single thing.

Your best bet might be to clone or deep clone the list so you actually have two separate instances. There are a lot of ways to do this and while this isn't the most efficient it's perhaps the simplest: https://stackoverflow.com/questions/129389/how-do-you-do-a-deep-copy-of-an-object-in-net-c-specifically

Interestingly enough I've run into this as well and while I don't remember exactly what I did I likely just cloned.

Thanks for your question, I like getting interest on this project.

**Comment by CodeLikeAManiac** [comment]
:) 
You are definitely right, this happens because  List<Customer> is a reference type  and acts as a pointer.
I also thought of cloning but I was worry about the performance impact. I need a solution generic that will apply to all partial classes having the attribute of Localization. 

The same applies with this library even though it is an excellent piece of work the fact that it uses Reflection it slows down the performance, for that reason I cache every translated object to avoid any performance cost.

I have resolved the issue described above yesterday but not with cloning, instead of caching the translated object as a whole I cache the object per translation with a distinctive key.
